changelog:
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: Enhancements
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
